---
services:
  blobqm:
    build: docker/blobqm
    container_name: blobqm
    environment:
      BLOB_PREFIX: landing
      CONTAINER_NAME: landing-archive
      LOG_LEVEL: INFO
      STORAGE_ACCOUNT_CONNECTION_STRING: "${ST_CONNECTION_STRING}"
      TOPICS_DIR: topics
