---
services:
  connect:
    container_name: connect
    depends_on:
      kafka:
        condition: service_healthy
    environment:
      CONNECT_BOOTSTRAP_SERVERS: kafka:29092
      CONNECT_GROUP_ID: external_kafka_connect_docker
      CONNECT_CONFIG_STORAGE_TOPIC: vault.infra.external.kafka_connect.default.config
      CONNECT_OFFSET_STORAGE_TOPIC: vault.infra.external.kafka_connect.default.offset
      CONNECT_STATUS_STORAGE_TOPIC: vault.infra.external.kafka_connect.default.status
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: "1"
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: "1"
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: "1"
      CONNECT_KEY_CONVERTER: org.apache.kafka.connect.storage.StringConverter
      CONNECT_VALUE_CONVERTER: org.apache.kafka.connect.converters.ByteArrayConverter
      CONNECT_REST_ADVERTISED_HOST_NAME: "connect"
      CONNECT_LOG4J_LOGGERS: "org.apache.qpid=DEBUG,io.cbdq=DEBUG,org.apache.kafka.connect.runtime.WorkerSinkTask=DEBUG"
      CONNECT_LOG4J_ROOT_LOGLEVEL: INFO
    image: ghcr.io/cbdq-io/kc-connectors:0.3.0
    ports:
      - 8083:8083
      - 9400:9400

  kafka:
    container_name: kafka
    environment:
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
      KAFKA_ADVERTISED_LISTENERS: 'INTERNAL://kafka:29092,EXTERNAL://localhost:9092'
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: false
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_INTER_BROKER_LISTENER_NAME: 'INTERNAL'
      KAFKA_LISTENERS: 'INTERNAL://kafka:29092,CONTROLLER://kafka:29093,EXTERNAL://0.0.0.0:9092'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT'
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
      KAFKA_MAX_REQUEST_SIZE: 4194352
      KAFKA_NODE_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      LOG_LEVEL: WARN
    healthcheck:
      test: kafka-topics --list --bootstrap-server kafka:9092
      interval: 1s
      retries: 30
    image: confluentinc/cp-kafka:7.6.2
    ports:
      - 9092:9092

  kccinit:
    depends_on:
      - router
    entrypoint: /usr/local/bin/kccinit.py
    environment:
      CONNECTOR_AzureServiceBusSink_AZURE_SERVICEBUS_CONNECTION_STRING: "${SBNS_CONNECTION_STRING}"
      CONNECTOR_AzureServiceBusSink_CONNECTOR_CLASS: io.cbdq.AzureServiceBusSinkConnector
      CONNECTOR_AzureServiceBusSink_CONSUMER_OVERRIDE_AUTO_OFFSET_RESET: earliest
      CONNECTOR_AzureServiceBusSink_RETRY_MAX_ATTEMPTS: "5"
      CONNECTOR_AzureServiceBusSink_RETRY_WAIT_TIME_MS: "1000"
      CONNECTOR_AzureServiceBusSink_TASKS_MAX: "1"
      CONNECTOR_AzureServiceBusSink_TOPIC_RENAME_FORMAT: "landing.$${topic}"
      CONNECTOR_AzureServiceBusSink_TOPICS: "topic.0,topic.1,topic.2,topic.3,topic.4,topic.5,topic.6,topic.7,topic.8,topic.9"
      KAFKA_CONNECT_ENDPOINT: "http://connect:8083"
      LOG_LEVEL: DEBUG
    image: ghcr.io/cbdq-io/kc-connectors:0.3.0

  router:
    build: docker/router
    container_name: router
    environment:
      LOG_LEVEL: INFO
      ROUTER_CUSTOM_SENDER: "custom:custom_sender"
      ROUTER_NAMESPACE_GB_CONNECTION_STRING: "${SBNS_CONNECTION_STRING}"
      ROUTER_NAMESPACE_IE_CONNECTION_STRING: "${SBNS_CONNECTION_STRING}"
      ROUTER_RULE_GB_TOPIC_0: '{ "destination_namespaces": "GB", "destination_topics": "routed.topic.0", "jmespath": "country", "regexp": "^GB$", "source_subscription": "router", "source_topic": "landing.topic.0"}'
      ROUTER_RULE_IE_TOPIC_0: '{ "destination_namespaces": "IE", "destination_topics": "routed.topic.0", "jmespath": "country", "regexp": "^IE$", "source_subscription": "router", "source_topic": "landing.topic.0"}'
      ROUTER_RULE_GB_TOPIC_1: '{ "destination_namespaces": "GB", "destination_topics": "routed.topic.1", "jmespath": "country", "regexp": "^GB$", "source_subscription": "router", "source_topic": "landing.topic.1"}'
      ROUTER_RULE_IE_TOPIC_1: '{ "destination_namespaces": "IE", "destination_topics": "routed.topic.1", "jmespath": "country", "regexp": "^IE$", "source_subscription": "router", "source_topic": "landing.topic.1"}'
      ROUTER_RULE_GB_TOPIC_2: '{ "destination_namespaces": "GB", "destination_topics": "routed.topic.2", "jmespath": "country", "regexp": "^GB$", "source_subscription": "router", "source_topic": "landing.topic.2"}'
      ROUTER_RULE_IE_TOPIC_2: '{ "destination_namespaces": "IE", "destination_topics": "routed.topic.2", "jmespath": "country", "regexp": "^IE$", "source_subscription": "router", "source_topic": "landing.topic.2"}'
      ROUTER_RULE_GB_TOPIC_3: '{ "destination_namespaces": "GB", "destination_topics": "routed.topic.3", "jmespath": "country", "regexp": "^GB$", "source_subscription": "router", "source_topic": "landing.topic.3"}'
      ROUTER_RULE_IE_TOPIC_3: '{ "destination_namespaces": "IE", "destination_topics": "routed.topic.3", "jmespath": "country", "regexp": "^IE$", "source_subscription": "router", "source_topic": "landing.topic.3"}'
      ROUTER_RULE_GB_TOPIC_4: '{ "destination_namespaces": "GB", "destination_topics": "routed.topic.4", "jmespath": "country", "regexp": "^GB$", "source_subscription": "router", "source_topic": "landing.topic.4"}'
      ROUTER_RULE_IE_TOPIC_4: '{ "destination_namespaces": "IE", "destination_topics": "routed.topic.4", "jmespath": "country", "regexp": "^IE$", "source_subscription": "router", "source_topic": "landing.topic.4"}'
      ROUTER_RULE_GB_TOPIC_5: '{ "destination_namespaces": "GB", "destination_topics": "routed.topic.5", "jmespath": "country", "regexp": "^GB$", "source_subscription": "router", "source_topic": "landing.topic.5"}'
      ROUTER_RULE_IE_TOPIC_5: '{ "destination_namespaces": "IE", "destination_topics": "routed.topic.5", "jmespath": "country", "regexp": "^IE$", "source_subscription": "router", "source_topic": "landing.topic.5"}'
      ROUTER_RULE_GB_TOPIC_6: '{ "destination_namespaces": "GB", "destination_topics": "routed.topic.6", "jmespath": "country", "regexp": "^GB$", "source_subscription": "router", "source_topic": "landing.topic.6"}'
      ROUTER_RULE_IE_TOPIC_6: '{ "destination_namespaces": "IE", "destination_topics": "routed.topic.6", "jmespath": "country", "regexp": "^IE$", "source_subscription": "router", "source_topic": "landing.topic.6"}'
      ROUTER_RULE_GB_TOPIC_7: '{ "destination_namespaces": "GB", "destination_topics": "routed.topic.7", "jmespath": "country", "regexp": "^GB$", "source_subscription": "router", "source_topic": "landing.topic.7"}'
      ROUTER_RULE_IE_TOPIC_7: '{ "destination_namespaces": "IE", "destination_topics": "routed.topic.7", "jmespath": "country", "regexp": "^IE$", "source_subscription": "router", "source_topic": "landing.topic.7"}'
      ROUTER_RULE_GB_TOPIC_8: '{ "destination_namespaces": "GB", "destination_topics": "routed.topic.8", "jmespath": "country", "regexp": "^GB$", "source_subscription": "router", "source_topic": "landing.topic.8"}'
      ROUTER_RULE_IE_TOPIC_8: '{ "destination_namespaces": "IE", "destination_topics": "routed.topic.8", "jmespath": "country", "regexp": "^IE$", "source_subscription": "router", "source_topic": "landing.topic.8"}'
      ROUTER_RULE_GB_TOPIC_9: '{ "destination_namespaces": "GB", "destination_topics": "routed.topic.9", "jmespath": "country", "regexp": "^GB$", "source_subscription": "router", "source_topic": "landing.topic.9"}'
      ROUTER_RULE_IE_TOPIC_9: '{ "destination_namespaces": "IE", "destination_topics": "routed.topic.9", "jmespath": "country", "regexp": "^IE$", "source_subscription": "router", "source_topic": "landing.topic.9"}'
      ROUTER_SOURCE_CONNECTION_STRING: "${SBNS_CONNECTION_STRING}"
